import Head from "next/head";
import useColorMode from "../hooks/useColorMode";

const ColorButton = ({ className, themeName, children, selectedClasses }) => {
  const { colorMode, setColorMode } = useColorMode();
  const selected = themeName === colorMode;
  return (
    <button
      className={`${className} bg-gradient-to-br rounded-md text-white font-semibold text-lg w-24 h-24 hover:shadow-lg focus:shadow-lg ${
        selected ? `ring-2 ring-offset-2 ${selectedClasses}` : ""
      } focus:outline-none focus:ring-2 focus:ring-offset-2`}
      onClick={() => setColorMode(themeName)}
    >
      {children}
    </button>
  );
};

const Home = () => {
  return (
    <div>
      <Head>
        <title>Tailwind Themes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={
          "w-full h-full min-h-screen flex items-center justify-center bg-gray-200 red:bg-red-100 orange:bg-orange-100 yellow:bg-yellow-100 green:bg-green-100 blue:bg-blue-100 indigo:bg-indigo-100 purple:bg-purple-100"
        }
      >
        <div
          className={
            "flex items-center justify-center w-max mx-auto bg-white rounded-lg"
          }
        >
          <div className={"grid w-full h-full p-8 grid-cols-3 gap-8"}>
            <ColorButton
              className={"from-red-300 to-red-500 focus:ring-red-400"}
              selectedClasses={"ring-red-400"}
              themeName={"red"}
            >
              Red
            </ColorButton>
            <ColorButton
              className={"from-orange-300 to-orange-500 focus:ring-orange-400"}
              selectedClasses={"ring-orange-400"}
              themeName={"orange"}
            >
              Orange
            </ColorButton>
            <ColorButton
              className={"from-yellow-300 to-yellow-500 focus:ring-yellow-400"}
              selectedClasses={"ring-yellow-400"}
              themeName={"yellow"}
            >
              Yellow
            </ColorButton>
            <ColorButton
              className={"from-green-300 to-green-500 focus:ring-green-400"}
              selectedClasses={"ring-green-400"}
              themeName={"green"}
            >
              Green
            </ColorButton>
            <ColorButton
              className={"from-blue-300 to-blue-500 focus:ring-blue-400"}
              selectedClasses={"ring-blue-400"}
              themeName={"blue"}
            >
              Blue
            </ColorButton>
            <ColorButton
              className={"from-indigo-300 to-indigo-500 focus:ring-indigo-400"}
              selectedClasses={"ring-indigo-400"}
              themeName={"indigo"}
            >
              Indigo
            </ColorButton>
            <ColorButton
              className={"from-purple-300 to-purple-500 focus:ring-purple-400"}
              selectedClasses={"ring-purple-400"}
              themeName={"purple"}
            >
              Purple
            </ColorButton>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
